// Code generated by generate-map.go for Analysis. DO NOT EDIT.

package lattice

import "Goat/analysis/defs"

type AnalysisLattice struct {
	mapLatticeBase
}

func (m *AnalysisLattice) Eq(o Lattice) bool {
	switch o := o.(type) {
	case *AnalysisLattice:
		return true
	case *Lifted:
		return m.Eq(o.Lattice)
	case *Dropped:
		return m.Eq(o.Lattice)
	default:
		return false
	}
}

func (m *AnalysisLattice) Top() Element {
	panic(errUnsupportedOperation)
}

func (m *AnalysisLattice) Analysis() *AnalysisLattice {
	return m
}

type Analysis struct {
	element
	base baseMap
}

// Map methods
func (w Analysis) Size() int {
	return w.base.Size()
}

func (w Analysis) Height() int {
	return w.base.Height()
}

func (w Analysis) Get(key defs.Superloc) (AnalysisState, bool) {
	v, found := w.base.Get(key)
	return v.(AnalysisState), found
}

func (w Analysis) GetOrDefault(key defs.Superloc, dflt AnalysisState) AnalysisState {
	return w.base.GetOrDefault(key, dflt).(AnalysisState)
}

func (w Analysis) GetUnsafe(key defs.Superloc) AnalysisState {
	return w.base.GetUnsafe(key).(AnalysisState)
}

func (w Analysis) Update(key defs.Superloc, value AnalysisState) Analysis {
	w.base = w.base.Update(key, value)
	return w
}

func (w Analysis) WeakUpdate(key defs.Superloc, value AnalysisState) Analysis {
	w.base = w.base.WeakUpdate(key, value)
	return w
}

func (w Analysis) Remove(key defs.Superloc) Analysis {
	w.base = w.base.Remove(key)
	return w
}

func (w Analysis) ForEach(f func(defs.Superloc, AnalysisState)) {
	w.base.ForEach(func(key interface{}, value Element) {
		f(key.(defs.Superloc), value.(AnalysisState))
	})
}

func (w Analysis) Find(f func(defs.Superloc, AnalysisState) bool) (zk defs.Superloc, zv AnalysisState, b bool) {
	k, e, found := w.base.Find(func(k interface{}, e Element) bool {
		return f(k.(defs.Superloc), e.(AnalysisState))
	})
	if found {
		return k.(defs.Superloc), e.(AnalysisState), true
	}
	return zk, zv, b
}

// Lattice element methods
func (w Analysis) Leq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "⊑")
	return w.leq(e)
}

func (w Analysis) leq(e Element) bool {
	return w.base.leq(e.(Analysis).base)
}

func (w Analysis) Geq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "⊒")
	return w.geq(e)
}

func (w Analysis) geq(e Element) bool {
	return w.base.geq(e.(Analysis).base)
}

func (w Analysis) Eq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "=")
	return w.eq(e)
}

func (w Analysis) eq(e Element) bool {
	return w.base.eq(e.(Analysis).base)
}

func (w Analysis) Join(o Element) Element {
	checkLatticeMatch(w.lattice, o.Lattice(), "⊔")
	return w.join(o)
}

func (w Analysis) join(o Element) Element {
	return w.MonoJoin(o.(Analysis))
}

func (w Analysis) MonoJoin(o Analysis) Analysis {
	w.base = w.base.MonoJoin(o.base)
	return w
}

func (w Analysis) Meet(o Element) Element {
	panic(errUnsupportedOperation)
}

func (w Analysis) meet(o Element) Element {
	panic(errUnsupportedOperation)
}

func (w Analysis) String() string {
	return w.base.String()
}

// Type conversion
func (w Analysis) Analysis() Analysis {
	return w
}
