// Code generated by generate-map.go for Charges. DO NOT EDIT.

package lattice

import "Goat/analysis/defs"

type ChargesLattice struct {
	mapLatticeBase
}

func (m *ChargesLattice) Eq(o Lattice) bool {
	switch o := o.(type) {
	case *ChargesLattice:
		return true
	case *Lifted:
		return m.Eq(o.Lattice)
	case *Dropped:
		return m.Eq(o.Lattice)
	default:
		return false
	}
}

func (m *ChargesLattice) Top() Element {
	panic(errUnsupportedOperation)
}

func (m *ChargesLattice) Charges() *ChargesLattice {
	return m
}

type Charges struct {
	element
	base baseMap
}

// Map methods
func (w Charges) Size() int {
	return w.base.Size()
}

func (w Charges) Height() int {
	return w.base.Height()
}

func (w Charges) Get(key defs.CtrLoc) (twoElementLatticeElement, bool) {
	v, found := w.base.Get(key)
	return v.(twoElementLatticeElement), found
}

func (w Charges) GetOrDefault(key defs.CtrLoc, dflt twoElementLatticeElement) twoElementLatticeElement {
	return w.base.GetOrDefault(key, dflt).(twoElementLatticeElement)
}

func (w Charges) GetUnsafe(key defs.CtrLoc) twoElementLatticeElement {
	return w.base.GetUnsafe(key).(twoElementLatticeElement)
}

func (w Charges) Update(key defs.CtrLoc, value twoElementLatticeElement) Charges {
	w.base = w.base.Update(key, value)
	return w
}

func (w Charges) WeakUpdate(key defs.CtrLoc, value twoElementLatticeElement) Charges {
	w.base = w.base.WeakUpdate(key, value)
	return w
}

func (w Charges) Remove(key defs.CtrLoc) Charges {
	w.base = w.base.Remove(key)
	return w
}

func (w Charges) ForEach(f func(defs.CtrLoc, twoElementLatticeElement)) {
	w.base.ForEach(func(key interface{}, value Element) {
		f(key.(defs.CtrLoc), value.(twoElementLatticeElement))
	})
}

func (w Charges) Find(f func(defs.CtrLoc, twoElementLatticeElement) bool) (zk defs.CtrLoc, zv twoElementLatticeElement, b bool) {
	k, e, found := w.base.Find(func(k interface{}, e Element) bool {
		return f(k.(defs.CtrLoc), e.(twoElementLatticeElement))
	})
	if found {
		return k.(defs.CtrLoc), e.(twoElementLatticeElement), true
	}
	return zk, zv, b
}

// Lattice element methods
func (w Charges) Leq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "⊑")
	return w.leq(e)
}

func (w Charges) leq(e Element) bool {
	return w.base.leq(e.(Charges).base)
}

func (w Charges) Geq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "⊒")
	return w.geq(e)
}

func (w Charges) geq(e Element) bool {
	return w.base.geq(e.(Charges).base)
}

func (w Charges) Eq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "=")
	return w.eq(e)
}

func (w Charges) eq(e Element) bool {
	return w.base.eq(e.(Charges).base)
}

func (w Charges) Join(o Element) Element {
	checkLatticeMatch(w.lattice, o.Lattice(), "⊔")
	return w.join(o)
}

func (w Charges) join(o Element) Element {
	return w.MonoJoin(o.(Charges))
}

func (w Charges) MonoJoin(o Charges) Charges {
	w.base = w.base.MonoJoin(o.base)
	return w
}

func (w Charges) Meet(o Element) Element {
	panic(errUnsupportedOperation)
}

func (w Charges) meet(o Element) Element {
	panic(errUnsupportedOperation)
}

func (w Charges) String() string {
	return w.base.String()
}

// Type conversion
func (w Charges) Charges() Charges {
	return w
}
