// Code generated by generate-map.go for ThreadCharges. DO NOT EDIT.

package lattice

import "Goat/analysis/defs"

type ThreadChargesLattice struct {
	mapLatticeBase
}

func (m *ThreadChargesLattice) Eq(o Lattice) bool {
	switch o := o.(type) {
	case *ThreadChargesLattice:
		return true
	case *Lifted:
		return m.Eq(o.Lattice)
	case *Dropped:
		return m.Eq(o.Lattice)
	default:
		return false
	}
}

func (m *ThreadChargesLattice) Top() Element {
	panic(errUnsupportedOperation)
}

func (m *ThreadChargesLattice) ThreadCharges() *ThreadChargesLattice {
	return m
}

type ThreadCharges struct {
	element
	base baseMap
}

// Map methods
func (w ThreadCharges) Size() int {
	return w.base.Size()
}

func (w ThreadCharges) Height() int {
	return w.base.Height()
}

func (w ThreadCharges) Get(key defs.Goro) (Charges, bool) {
	v, found := w.base.Get(key)
	return v.(Charges), found
}

func (w ThreadCharges) GetOrDefault(key defs.Goro, dflt Charges) Charges {
	return w.base.GetOrDefault(key, dflt).(Charges)
}

func (w ThreadCharges) GetUnsafe(key defs.Goro) Charges {
	return w.base.GetUnsafe(key).(Charges)
}

func (w ThreadCharges) Update(key defs.Goro, value Charges) ThreadCharges {
	w.base = w.base.Update(key, value)
	return w
}

func (w ThreadCharges) WeakUpdate(key defs.Goro, value Charges) ThreadCharges {
	w.base = w.base.WeakUpdate(key, value)
	return w
}

func (w ThreadCharges) Remove(key defs.Goro) ThreadCharges {
	w.base = w.base.Remove(key)
	return w
}

func (w ThreadCharges) ForEach(f func(defs.Goro, Charges)) {
	w.base.ForEach(func(key interface{}, value Element) {
		f(key.(defs.Goro), value.(Charges))
	})
}

func (w ThreadCharges) Find(f func(defs.Goro, Charges) bool) (zk defs.Goro, zv Charges, b bool) {
	k, e, found := w.base.Find(func(k interface{}, e Element) bool {
		return f(k.(defs.Goro), e.(Charges))
	})
	if found {
		return k.(defs.Goro), e.(Charges), true
	}
	return zk, zv, b
}

// Lattice element methods
func (w ThreadCharges) Leq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "⊑")
	return w.leq(e)
}

func (w ThreadCharges) leq(e Element) bool {
	return w.base.leq(e.(ThreadCharges).base)
}

func (w ThreadCharges) Geq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "⊒")
	return w.geq(e)
}

func (w ThreadCharges) geq(e Element) bool {
	return w.base.geq(e.(ThreadCharges).base)
}

func (w ThreadCharges) Eq(e Element) bool {
	checkLatticeMatch(w.lattice, e.Lattice(), "=")
	return w.eq(e)
}

func (w ThreadCharges) eq(e Element) bool {
	return w.base.eq(e.(ThreadCharges).base)
}

func (w ThreadCharges) Join(o Element) Element {
	checkLatticeMatch(w.lattice, o.Lattice(), "⊔")
	return w.join(o)
}

func (w ThreadCharges) join(o Element) Element {
	return w.MonoJoin(o.(ThreadCharges))
}

func (w ThreadCharges) MonoJoin(o ThreadCharges) ThreadCharges {
	w.base = w.base.MonoJoin(o.base)
	return w
}

func (w ThreadCharges) Meet(o Element) Element {
	panic(errUnsupportedOperation)
}

func (w ThreadCharges) meet(o Element) Element {
	panic(errUnsupportedOperation)
}

func (w ThreadCharges) String() string {
	return w.base.String()
}

// Type conversion
func (w ThreadCharges) ThreadCharges() ThreadCharges {
	return w
}
