// Code generated by generate-hasher.go for CtrLoc. DO NOT EDIT

package defs

import (
	"log"
)

type hasherCtrLoc struct{}

func (hasherCtrLoc) cast(elem interface{}) CtrLoc {
	loc, ok := elem.(CtrLoc)
	if !ok {
		log.Fatalf("ControlLocation hasher was given non-ControlLocation: %T %v\n", elem, elem)
	}
	return loc
}

func (h hasherCtrLoc) Equal(a, b interface{}) bool {
	return h.cast(a).Equal(h.cast(b))
}

func (h hasherCtrLoc) Hash(key interface{}) uint32 {
	return h.cast(key).Hash()
}
