// Code generated by generate-hasher.go for goro. DO NOT EDIT

package defs

import (
	"log"
)

type hashergoro struct{}

func (hashergoro) cast(elem interface{}) Goro {
	loc, ok := elem.(Goro)
	if !ok {
		log.Fatalf("Goroutine hasher was given non-Goroutine: %T %v\n", elem, elem)
	}
	return loc
}

func (h hashergoro) Equal(a, b interface{}) bool {
	return h.cast(a).Equal(h.cast(b))
}

func (h hashergoro) Hash(key interface{}) uint32 {
	return h.cast(key).Hash()
}
