// Code generated by generate-hasher.go for Superloc. DO NOT EDIT

package defs

import (
	"log"
)

type hasherSuperloc struct{}

func (hasherSuperloc) cast(elem interface{}) Superloc {
	loc, ok := elem.(Superloc)
	if !ok {
		log.Fatalf("Superlocation hasher was given non-Superlocation: %T %v\n", elem, elem)
	}
	return loc
}

func (h hasherSuperloc) Equal(a, b interface{}) bool {
	return h.cast(a).Equal(h.cast(b))
}

func (h hasherSuperloc) Hash(key interface{}) uint32 {
	return h.cast(key).Hash()
}
